name: fluoroseg
channels:
  - pytorch
  - "nvidia/label/cuda-12.8.0"
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cuda-toolkit=12.8
  - pip
  - pip:
    - flake8
    - black
    - -e .